### ISSUE TITLE
[로그인 화면] 로그인 검증 구현하기

### ISSUE THREAD

**Issue by wudys** [woowa-techcamp-2020/market-14#4]
- [x] 로그인 결과 표시하는 UI 구현하기
- [x] 로그인 검증 구현하기
- [x] API 연결

**Comment by hanSong2** [comment]
덤으로 로그아웃도 구현했습니당;;

**Comment by wudys** [comment]
58b6cf177ada0ec2ef4cce93c5cc26c1c450f0a5
